### ISSUE TITLE
npm run error

### ISSUE THREAD

**Issue by Rakeshvcr** [mjyc/head-pose-estimation-demo#2]
getting this error while running npm
Lifecycle scripts included in head-pose-estimation-using-opencvjs-and-tensorflowjs-posenet:
  start
    parcel index.html --open

available via `npm run-script`:
  build
    parcel build index.html

**Comment by mjyc** [comment]
The problem seems to be coming from using parcel-bundler. Fixed the issue by using browserify instead; see https://github.com/mjyc/head-pose-estimation-demo/commit/3d6a7c3be4fc83f1b7d9cbc6ad5be0592a7f7b84

Please reopen if you are continue to having problems with the latest master branch code.
