### ISSUE TITLE
What is the source of the hack that you mentioned here?

### ISSUE THREAD

**Issue by kafan1986** [mjyc/head-pose-estimation-demo#3]
Where do you get the idea for this hack for initialization values of tvec and rvec?

https://github.com/mjyc/head-pose-estimation-demo/blob/3300c990680b7262088f64f83687d64f7057520e/src/index.js#L116

**Comment by mjyc** [comment]
Since most people are looking at the camera when they open an web app that runs this code, I set the initial transformation values to represent a face located in the center of the camera and looking at the camera. I just came up with the idea, there is no "source". I hope my explanation helps you.
