### ISSUE TITLE
import opencv.js

### ISSUE THREAD

**Issue by minkyokyo** [mjyc/head-pose-estimation-demo#4]
Hello!
My question is very basic, but I would appreciate it if you could answer it.
I am developing with three.js and opencv.js.
How did you import the opencv.js file?

https://docs.opencv.org/3.4/d4/da1/tutorial_js_setup.html
If I build opencv.js like the link above, can I import opencv.js like your javascript file?

Thank you.

**Comment by mjyc** [comment]
Thanks for your interests in this project.

> If I build opencv.js like the link above, can I import opencv.js like your javascript file?

I haven't tried instructions in the doc, but looking at how it uses [Emscripten](https://emscripten.org/docs/porting/emscripten-runtime-environment.html) you should be able to import compiled opencv.js modules. Note that I used https://github.com/mjyc/opencv which exposed [solvePnP](https://docs.opencv.org/3.4.5/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d) and [projectPoints](https://docs.opencv.org/3.4.5/d9/d0c/group__calib3d.html#ga1019495a2c8d1743ed5cc23fa0daff8c) methods in [calib3d](https://docs.opencv.org/3.4.5/d9/d0c/group__calib3d.html) module used in this demo.
